name: kirei

description: "Japanese Beauty Products Store in Bangladesh â€“ Authentic Products..."

publish_to: 'none'

version: 4.0.4+45



environment:
  sdk: '>=3.7.0 <4.0.0'

#----------Packages----------#
dependencies:
  flutter:
    sdk: flutter


  #Utility Packages
  http: ^1.4.0
  dotted_border: ^3.1.0
  intl: any
  logger: ^2.6.0
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.3
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  webview_flutter: ^4.13.0
  fluttertoast: ^8.2.12
  flutter_dotenv: ^5.2.1
  shimmer: ^3.0.0
  gap: ^3.0.1
  package_info_plus: ^8.3.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  convex_bottom_bar: ^3.2.0
  flutter_typeahead: ^5.2.0
  expandable: ^5.0.1
  flutter_widget_from_html_core: ^0.16.0
  badges: ^3.1.2
  font_awesome_flutter: ^10.8.0
  percent_indicator: ^4.2.5
  image_picker: ^1.1.2
  share_plus: ^11.0.0
  insta_image_viewer: ^1.0.4
  flutter_facebook_auth: ^7.1.2
  sign_in_with_apple: ^7.0.1
  flutter_fortune_wheel: ^1.3.2
  like_button: ^2.1.0
  comment_box: ^0.0.18
  flutter_local_notifications: ^19.3.0
  gtm: ^1.0.2
  facebook_app_events: ^0.20.1
  clipboard: ^0.1.3
  youtube_player_iframe: ^5.2.1
  device_info_plus: ^11.5.0
  slide_countdown: ^2.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.5.4


  # Icons
  cupertino_icons: ^1.0.8


  #State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  # Localization
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^3.15.0
  google_sign_in: ^7.1.0
  firebase_auth: ^5.6.1
  firebase_messaging: ^15.2.8
  firebase_analytics: ^11.5.1
  app_links: ^6.4.0
  firebase_crashlytics: ^4.3.8
  flutter_timer_countdown: ^1.0.7





#  cloud_firestore: ^4.15.10


  # Awesome plugins
#  awesome_notifications_core: ^0.8.0
#  awesome_notifications: ^0.8.0
#  awesome_notifications_fcm: ^0.8.0



dev_dependencies:
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:

  generate: true
  uses-material-design: true

  # Local Assets
  assets:
    - assets/images/placeholder.png
    - assets/images/logos/
    - assets/images/icons/
    - assets/images/banners/
    - assets/images/on_boarding_images/
    - assets/images/recommendation/
    - assets/images/demo/
    - assets/images/background/
    - .env


  # Local Fonts
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans.ttf
        - asset: assets/fonts/WorkSans-Italic.ttf

    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay-Regular.otf
        - asset: assets/fonts/ClashDisplay-Medium.otf
        - asset: assets/fonts/ClashDisplay-Bold.otf

