name: kirei

description: "Japanese Beauty Products Store in Bangladesh â€“ Authentic Products..."

publish_to: 'none'

version: 3.0.0+30


environment:
  sdk: '>=3.3.1 <4.0.0'

#----------Packages----------#
dependencies:
  flutter:
    sdk: flutter


  #Utility Packages
  http: ^1.2.1
  intl: any
  logger: ^2.1.0
  url_launcher: ^6.2.5
  connectivity_plus: ^5.0.2
  connection_notifier: ^2.0.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  custom_refresh_indicator: ^3.1.0
  webview_flutter: ^4.7.0
  fluttertoast: ^8.2.4
  flutter_dotenv: ^5.1.0
  shimmer: ^3.0.0
  gap: ^3.0.1
  package_info_plus: ^6.0.0
  upgrader: 10.3.0
  printing: ^5.12.0
  open_file: ^3.3.2
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.1
  convex_bottom_bar: ^3.2.0
  flutter_typeahead: ^5.2.0
  expandable: ^5.0.1
  flutter_widget_from_html_core: ^0.14.12
  badges: ^3.1.2
  font_awesome_flutter: ^10.7.0
  percent_indicator: ^4.2.3
  image_picker: ^1.1.1
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  insta_image_viewer: ^1.0.4
  flutter_facebook_auth: ^7.0.1
  sign_in_with_apple: ^6.1.1
  flutter_fortune_wheel: ^1.3.1
  like_button: ^2.0.5
  comment_box: ^0.0.18
  flutter_local_notifications: ^17.2.1+2
  gtm: ^0.1.6
  facebook_app_events: ^0.19.2
  clipboard: ^0.1.3
  youtube_player_iframe: ^5.1.2



  # Icons
  cupertino_icons: ^1.0.6


  #State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Localization
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.18.0
  firebase_messaging: ^14.7.20
  firebase_analytics: ^10.10.7
  app_links: ^6.3.2



#  cloud_firestore: ^4.15.10


  # Awesome plugins
#  awesome_notifications_core: ^0.8.0
#  awesome_notifications: ^0.8.0
#  awesome_notifications_fcm: ^0.8.0

  # Payment Gateway


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  generate: true
  uses-material-design: true

  # Local Assets
  assets:
    - assets/images/placeholder.png
    - assets/images/logos/
    - assets/images/icons/
    - assets/images/banners/
    - assets/images/on_boarding_images/
    - assets/images/recommendation/
    - assets/images/demo/
    - assets/images/background/
    - .env


  # Local Fonts
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
