name: kirei
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.12+16


environment:
  sdk: '>=3.3.1 <4.0.0'

#----------Packages----------#
dependencies:
  flutter:
    sdk: flutter


  #Utility Packages
  http: ^1.2.1
  intl: any
  logger: ^2.1.0
  lottie: ^3.1.0
  url_launcher: ^6.2.5
  connectivity_plus: ^5.0.2
  connection_notifier: ^2.0.1
  carousel_slider: ^4.2.1
  another_flushbar: ^1.12.30
  smooth_page_indicator: ^1.1.0
  persistent_bottom_nav_bar: any
  persistent_bottom_nav_bar_v2: any
  syncfusion_flutter_pdfviewer: ^24.2.8
  custom_refresh_indicator: ^3.1.0
  appinio_video_player: ^1.2.2
  syncfusion_flutter_charts: ^24.2.9
  webview_flutter: ^4.7.0
  buttons_tabbar: ^1.3.8
  loader_overlay: ^4.0.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  shimmer: ^3.0.0
  fl_chart: ^0.66.2
  gap: ^3.0.1
  package_info_plus: ^6.0.0
  flutter_dynamic_icon: ^2.1.0
  flutter_app_badger: ^1.5.0
  awesome_notifications: ^0.8.2
  upgrader: ^10.1.0
  pdf: ^3.10.8
  path_provider: ^2.1.3
  printing: ^5.12.0
  open_file: ^3.3.2
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.1
  convex_bottom_bar: ^3.2.0
  flutter_typeahead: ^5.2.0
  expandable: ^5.0.1
  flutter_widget_from_html_core: ^0.14.12
  badges: ^3.1.2
  font_awesome_flutter: ^10.7.0
  percent_indicator: ^4.2.3
  mime: ^1.0.5
  http_parser: ^4.0.2
  image_picker: ^1.1.1
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  insta_image_viewer: ^1.0.4

  # Icons
  cupertino_icons: ^1.0.6


  #State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Localization
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.18.0
  firebase_messaging: ^14.7.20
  cloud_firestore: ^4.15.10

  # Payment Gateway
  flutter_bkash: ^0.2.0
  flutter_stripe: ^10.1.1
  flutter_sslcommerz: ^2.2.2-nullsafety.0
  flutter_facebook_auth: ^7.0.1
  sign_in_with_apple: ^6.1.1
  firebase_analytics: ^10.10.7
  firebase_dynamic_links: ^5.5.7
  go_router: ^13.2.5
  app_links: ^6.1.4













dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  generate: true
  uses-material-design: true

  # Local Assets
  assets:
    - assets/images/logos/
    - assets/images/icons/
    - assets/images/banners/
    - assets/images/animations/
    - assets/images/on_boarding_images/
    - assets/images/pdf_a/
    - assets/images/recommendation/
    - .env


  # Local Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         styles: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
