name: kirei
description: "Japanese Beauty Products Store in Bangladesh â€“ Authentic Products..."
publish_to: 'none'

version: 6.0.4+59


environment:
  sdk: '>=3.10.0 <4.0.0'

#----------Packages----------#
dependencies:
  flutter:
    sdk: flutter


  #Utility Packages
  http: ^1.6.0
  intl: any
  logger: ^2.6.2
  url_launcher: ^6.3.2
  connectivity_plus: ^7.0.0
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^2.0.1
  webview_flutter: ^4.13.0
  fluttertoast: ^9.0.0
  flutter_dotenv: ^6.0.0
  shimmer: ^3.0.0
  gap: ^3.0.1
  package_info_plus: ^9.0.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  flutter_typeahead: ^5.2.0
  expandable: ^5.0.1
  flutter_widget_from_html_core: ^0.17.0
  badges: ^3.1.2
  percent_indicator: ^4.2.5
  image_picker: ^1.2.1
  share_plus: ^12.0.1
  insta_image_viewer: ^1.0.4
#  flutter_facebook_auth: ^7.1.2
  sign_in_with_apple: ^7.0.1
  flutter_fortune_wheel: ^1.3.2
  like_button: ^2.1.0
  comment_box: ^0.0.18
  flutter_local_notifications: ^19.5.0
  facebook_app_events: ^0.24.0
  clipboard: ^3.0.8
  youtube_player_iframe: ^5.2.2
  device_info_plus: ^12.3.0
  slide_countdown: ^2.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: any


  # Icons
  cupertino_icons: ^1.0.8


  #State Management
  get: ^4.7.3
  get_storage: ^2.1.1
  hugeicons: ^1.1.4
  google_nav_bar: ^5.0.7
  flutter_timer_countdown: ^1.0.7


  # Localization
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^4.3.0
  google_sign_in: ^7.2.0
  firebase_auth: ^6.1.3
  firebase_messaging: ^16.1.0
  firebase_analytics: ^12.1.0
  app_links: ^7.0.0
  firebase_crashlytics: ^5.0.6


dev_dependencies:
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:

  generate: true
  uses-material-design: true

  # Local Assets
  assets:
    - assets/images/placeholder.png
    - assets/images/placeholder.jpg
    - assets/images/logos/
    - assets/images/icons/
    - assets/images/banners/
    - assets/images/on_boarding_images/
    - assets/images/recommendation/
    - assets/images/demo/
    - assets/images/background/
    - .env


  # Local Fonts
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans.ttf
        - asset: assets/fonts/WorkSans-Italic.ttf

    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay-Regular.otf
        - asset: assets/fonts/ClashDisplay-Medium.otf
        - asset: assets/fonts/ClashDisplay-Bold.otf

